version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg_clients
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pass_change_me
      POSTGRES_DB: clients_db
    ports:
      - "5432:5432"
    volumes:
      - pg_clients_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d clients_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_clients_data:
